### ISSUE TITLE
[Feature request] Bungeecord support

### ISSUE THREAD

**Issue by GeekCornerGH** [JustinDevB/AntiCheatReplay#16]
HI @JustinDevB,
your plugin is great, but I would like to get Bungeecord support, so I can easily tp to the server that have hackers to watch replays.
(Btw i'll give a star when this will be completed :D)
Thanks in advance for your answer
Have a great day

**Comment by JustinDevB** [comment]
I don't handle any of the logic involving playing a replay. That would be a request for AdvancedReplay.
