### ISSUE TITLE
Replays don't save when on 1.19

### ISSUE THREAD

**Issue by Budderman18** [JustinDevB/AntiCheatReplay#19]
Whenever a replay finishes, it does all the normal stuff. It will show the "a recording has been saved" message in chat, send a discord webhook, however it does not actually save the replay itself. No error message seems to show up either. I'm running Pufferfish 1.19 with Themis 0.13.0 if that helps.

**Comment by JustinDevB** [comment]
AdvancedReplay does not support 1.19 yet

https://github.com/Jumper251/AdvancedReplay

**Comment by JustinDevB** [comment]
@Budderman18 
I forked AdvancedReplay and updated it to 1.19. It will throw console errors, but recordings get created and save as expected. 
https://github.com/JustinDevB/AdvancedReplay/releases/tag/1.19
