### ISSUE TITLE
AntiCheatReplay not working with SoaromaSAC

### ISSUE THREAD

**Issue by LPSebi** [JustinDevB/AntiCheatReplay#20]
`AntiCheatReplay] Plugin AntiCheatReplay v2.7.2 has failed to register events for class me.justindevb.anticheatreplay.listeners.AntiCheats.SoaromaListener because me/korbsti/soaromaac/api/PunishmentEvent does not exist.`

**Comment by JustinDevB** [comment]
Soaroma dev broke their API, they need to change things for me to be able to support it again

**Comment by LPSebi** [comment]
Is that going to be happening soon?

**Comment by JustinDevB** [comment]
No clue, talk to their dev. I need something that fires when a player is flagged, and I need something that fires when the anticheat punishes a player.

**Comment by LPSebi** [comment]
### Answer from the dev:
![image](https://user-images.githubusercontent.com/52174534/178152595-2297fa50-1cb6-4b66-bb17-871548606c04.png)

**Comment by JustinDevB** [comment]
SoaromaFlagEvent does not contain any useful methods. Only other Event that gets passed from Soaroma is an admin punish event.

Due to lack of API support from Soaroma I have dropped support for this anticheat
