### ISSUE TITLE
Be able to only record a punishment (not a flag) VulcanAC

### ISSUE THREAD

**Issue by LPSebi** [JustinDevB/AntiCheatReplay#21]
It would be nice if you could add an option to disable recordings on flags and to only record a punishment.

**Comment by JustinDevB** [comment]
You would never see a recording if that were the case. If you kick or ban as a punishment, it would start recording after the player has already disconnected from the server.

**Comment by LPSebi** [comment]
Okay, that makes sense... Would you be able to add an option to only save the recording if the player got punished?

**Comment by JustinDevB** [comment]
That’s how the plugin works by default

**Comment by LPSebi** [comment]
Hmmm... For me, it records every flag. I'm using Vulcan.

**Comment by JustinDevB** [comment]
It’ll start recording on a flag, but only save if the player is punished.

**Comment by JustinDevB** [comment]
Shouldn’t cause a recording every single flag unless the player is disconnecting after flagging.

Do you have Always-Save-Recording set to true?

**Comment by LPSebi** [comment]
Oh yeah, my bad... Thanks!
