### ISSUE TITLE
Suspected player frozen inside of replay

### ISSUE THREAD

**Issue by kamber5** [JustinDevB/AntiCheatReplay#27]
Hi

We are having a issue with some of the replays being bugged. The player that is recorded for cheating is frozen in place and is not moving at all, the hit sounds can be heard.

Some of the replays are ok, but some are frozen like said above.
![image](https://github.com/JustinDevB/AntiCheatReplay/assets/35629701/9b5884a5-be08-40cc-b3f0-09012cd657c3)

Server version: git-Paper-550 (MC: 1.19.4)
Anti Cheat hook: Vulcan

We are using the latest version of Advanced Replay and Anticheat Replay, currently they are with fully default configurations and the same problem is happening.

**Comment by JustinDevB** [comment]
This is an issue with AdvancedReplay, not my plugin. Send the dev of AdvancedReplay the file of the recording containing the frozen player so he can further debug the issue.
