### ISSUE TITLE
Recording-Length not working

### ISSUE THREAD

**Issue by LIWKK** [JustinDevB/AntiCheatReplay#8]
If you set the Recording-Length to like 5-10, the recording will never stop because you require cached player, but the player might already get banned in that time and they are not anymore in your player cache because you remove them 10 ticks after quit.

**Comment by JustinDevB** [comment]
Unable to reproduce an issue like this in my testing. I set my recording length to 5 and it recorded perfectly fine. Are you getting an error message?

**Comment by JustinDevB** [comment]
Unable to reproduce and no response. Closing this issue.
